### ISSUE TITLE
New update stops this from working

### ISSUE THREAD

**Issue by adminy** [ssttevee/funimation#2]
Funimation is in motion and their source code has been updated quite a lot. Have you given up on this project after commin thus far?

**Comment by Zebraslive** [comment]
the site's url structure for shows and episodes has changed, hope this script gets updated. Really need this to work.

**Comment by adminy** [comment]
Sorry, I'm no longer interested on ripping from them, They don't provide the best out there also they are easy to rip, I'm sure you'll find alternative solutions if you try.  There were other projects that give you direct links.
